### ISSUE TITLE
invalid argument "CarND-Term1"

### ISSUE THREAD

**Issue by kvasnyj** [domluna/CarND-Term1-Starter-Kit#14]
PS SDC\Repo\CarND-Term1-Starter-Kit> docker build -t CarND-Term1

invalid argument "CarND-Term1" for t: Error parsing reference: "CarND-Term1" is not a valid repository/tag
See 'docker build --help'.

**Comment by domluna** [comment]
@kvasnyj switched it to use no capital letters -> carnd-term1. Updated in latest commit.
