### ISSUE TITLE
docker instructions

### ISSUE THREAD

**Issue by giladgressel** [domluna/CarND-Term1-Starter-Kit#3]
@joshuacook should take a look at those more carefully.  We started a document for this actually.

I think the first command you list is not needed, and the second has one syntax error , the `pwd` needs to be `{pwd}`

here is the link to the doc we have working on this.
https://codeshare.io/axLBda

**Comment by joshuacook** [comment]
Looks like I wrote those or am the maintainer ...

**Comment by joshuacook** [comment]
These are not good docker instructions. Our students should *never* be using bash on their container. @domluna are you on slack where we can chat about this?

**Comment by giladgressel** [comment]
please pipe me into it, when/wherever it starts.  @joshuacook  can't you just replace this docker file with the one you had me running?

**Comment by giladgressel** [comment]
@yrahal  Just alerting you to this repo.  We are building a start-kit for the Term1 of SDC.  I saw your medium post on your docker, perhaps you'd like to help debug and contribute to this?
This will be the official repo/readme for the course when we are done.
thanks!

**Comment by joshuacook** [comment]
yes

**Comment by joshuacook** [comment]
Didn't mean to be harsh. Just I put *a ton* of work into this like three weeks ago. It looks like it was pulled from here: https://github.com/joshuacook/CarND-TensorFlow-L2

It should be but it also needs `run_jupyter.sh`

**Comment by domluna** [comment]
@joshuacook same name on Slack. Yeah the Dockerfile was pulled from the udacity/CarND-TensorFlow-L2 repo. I took out the jupyter part out because it seemed project specific but I could be wrong. For example the Behavioural cloning project doesn't use Jupyter at all.

**Comment by joshuacook** [comment]
I don't think we are on any shared slack teams.

**Comment by domluna** [comment]
Yeah just realised that ...

**Comment by joshuacook** [comment]
mlnd, nd889, carnd, ...

**Comment by domluna** [comment]
Does #9 solve this?

**Comment by giladgressel** [comment]
Yes I think so, except only for windows 10..... we still need to edit more for windows 8, where the tools aren't the same
perhaps an entirely new page is the way to go though

**Comment by joshuacook** [comment]
My understanding is that windows !10 uses Docker Toolbox which I think is bash and therefore just like mac/linux. I still think we should have a totally separate page.
